[package]
name = "rdf-canon"
authors = ["yamdan"]
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = "0.2"
indexmap = "1.9"
itertools = "0.10"
oxigraph = { git = "https://github.com/oxigraph/oxigraph.git", branch = "next" }
oxrdf = { git = "https://github.com/oxigraph/oxigraph.git", branch = "next" }
sha2 = "0.10"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3"

[features]
log = []
