[package]
name = "rdf-canon"
authors = ["yamdan"]
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = "0.2"
itertools = "0.10"
oxrdf = { git = "https://github.com/oxigraph/oxigraph.git", branch = "next", version = "0.2.0-alpha.1-dev" }
sha2 = "0.10"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", optional = true }

[dev-dependencies]
oxttl = { git = "https://github.com/oxigraph/oxigraph.git", branch = "next", version = "0.1.0-alpha.1-dev" }

[features]
log = ["tracing-subscriber"]
